{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Introduction\n",
    "\n",
    "This notebook attempts to replicate the results of the \"A unified framework for adverserial attack and defense in constrained feature space.\" paper by Simonetto, Cordy, et al (https://arxiv.org/abs/2112.01156). All work in this notebook was done by Jeff Schaack and Yoann Le Bihan for the AI & Cybersecurity course at the University of Luxembourg."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Setup\n",
    "\n",
    "Ensure that the conda environment has the ipykernel and jupyter packages installed and uses Python 3.8.8."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Cloning into './repository'...\n",
      "remote: Enumerating objects: 207, done.\u001b[K\n",
      "remote: Counting objects: 100% (207/207), done.\u001b[K\n",
      "remote: Compressing objects: 100% (142/142), done.\u001b[K\n",
      "remote: Total 207 (delta 64), reused 203 (delta 60), pack-reused 0 (from 0)\u001b[K\n",
      "Receiving objects: 100% (207/207), 4.18 MiB | 26.42 MiB/s, done.\n",
      "Resolving deltas: 100% (64/64), done.\n"
     ]
    }
   ],
   "source": [
    "!git clone https://github.com/serval-uni-lu/moeva2-ijcai22-replication.git ./repository"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: autograd==1.3 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from -r ./repository/requirements.txt (line 1)) (1.3)\n",
      "Requirement already satisfied: joblib==0.15.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from -r ./repository/requirements.txt (line 2)) (0.15.1)\n",
      "Requirement already satisfied: matplotlib==3.2.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from -r ./repository/requirements.txt (line 3)) (3.2.1)\n",
      "Requirement already satisfied: pandas==1.0.3 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from -r ./repository/requirements.txt (line 4)) (1.0.3)\n",
      "Requirement already satisfied: pymoo==0.4.2.2 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from -r ./repository/requirements.txt (line 5)) (0.4.2.2)\n",
      "Requirement already satisfied: tensorflow==2.5 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from -r ./repository/requirements.txt (line 6)) (2.5.0)\n",
      "Requirement already satisfied: scikit-learn==0.24.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from -r ./repository/requirements.txt (line 7)) (0.24.1)\n",
      "Requirement already satisfied: gurobipy==9.1.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from -r ./repository/requirements.txt (line 8)) (9.1.0)\n",
      "Requirement already satisfied: tqdm==4.54.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from -r ./repository/requirements.txt (line 9)) (4.54.1)\n",
      "Requirement already satisfied: adversarial-robustness-toolbox==1.7.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from adversarial-robustness-toolbox[tensorflow]==1.7.0->-r ./repository/requirements.txt (line 10)) (1.7.0)\n",
      "Requirement already satisfied: dvc==2.4.3 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (2.4.3)\n",
      "Requirement already satisfied: Pillow==8.3.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from -r ./repository/requirements.txt (line 12)) (8.3.0)\n",
      "Requirement already satisfied: pyrecorder==0.1.8 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from -r ./repository/requirements.txt (line 13)) (0.1.8)\n",
      "Requirement already satisfied: pytest in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from -r ./repository/requirements.txt (line 14)) (8.3.3)\n",
      "Requirement already satisfied: comet-ml==3.13.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from -r ./repository/requirements.txt (line 15)) (3.13.1)\n",
      "Requirement already satisfied: shap==0.39.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from -r ./repository/requirements.txt (line 16)) (0.39.0)\n",
      "Requirement already satisfied: imbalanced-learn==0.8.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from -r ./repository/requirements.txt (line 17)) (0.8.0)\n",
      "Requirement already satisfied: mergedeep==1.3.4 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from -r ./repository/requirements.txt (line 18)) (1.3.4)\n",
      "Requirement already satisfied: numpy>=1.12 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from autograd==1.3->-r ./repository/requirements.txt (line 1)) (1.19.5)\n",
      "Requirement already satisfied: future>=0.15.2 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from autograd==1.3->-r ./repository/requirements.txt (line 1)) (1.0.0)\n",
      "Requirement already satisfied: cycler>=0.10 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from matplotlib==3.2.1->-r ./repository/requirements.txt (line 3)) (0.12.1)\n",
      "Requirement already satisfied: kiwisolver>=1.0.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from matplotlib==3.2.1->-r ./repository/requirements.txt (line 3)) (1.4.7)\n",
      "Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from matplotlib==3.2.1->-r ./repository/requirements.txt (line 3)) (2.4.7)\n",
      "Requirement already satisfied: python-dateutil>=2.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from matplotlib==3.2.1->-r ./repository/requirements.txt (line 3)) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2017.2 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from pandas==1.0.3->-r ./repository/requirements.txt (line 4)) (2024.1)\n",
      "Requirement already satisfied: scipy>=1.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from pymoo==0.4.2.2->-r ./repository/requirements.txt (line 5)) (1.4.0)\n",
      "Requirement already satisfied: cma==2.7 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from pymoo==0.4.2.2->-r ./repository/requirements.txt (line 5)) (2.7.0)\n",
      "Requirement already satisfied: absl-py~=0.10 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from tensorflow==2.5->-r ./repository/requirements.txt (line 6)) (0.15.0)\n",
      "Requirement already satisfied: astunparse~=1.6.3 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from tensorflow==2.5->-r ./repository/requirements.txt (line 6)) (1.6.3)\n",
      "Requirement already satisfied: flatbuffers~=1.12.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from tensorflow==2.5->-r ./repository/requirements.txt (line 6)) (1.12)\n",
      "Requirement already satisfied: google-pasta~=0.2 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from tensorflow==2.5->-r ./repository/requirements.txt (line 6)) (0.2.0)\n",
      "Requirement already satisfied: h5py~=3.1.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from tensorflow==2.5->-r ./repository/requirements.txt (line 6)) (3.1.0)\n",
      "Requirement already satisfied: keras-preprocessing~=1.1.2 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from tensorflow==2.5->-r ./repository/requirements.txt (line 6)) (1.1.2)\n",
      "Requirement already satisfied: opt-einsum~=3.3.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from tensorflow==2.5->-r ./repository/requirements.txt (line 6)) (3.3.0)\n",
      "Requirement already satisfied: protobuf>=3.9.2 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from tensorflow==2.5->-r ./repository/requirements.txt (line 6)) (3.20.3)\n",
      "Requirement already satisfied: six~=1.15.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from tensorflow==2.5->-r ./repository/requirements.txt (line 6)) (1.15.0)\n",
      "Requirement already satisfied: termcolor~=1.1.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from tensorflow==2.5->-r ./repository/requirements.txt (line 6)) (1.1.0)\n",
      "Requirement already satisfied: typing-extensions~=3.7.4 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from tensorflow==2.5->-r ./repository/requirements.txt (line 6)) (3.7.4.3)\n",
      "Requirement already satisfied: wheel~=0.35 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from tensorflow==2.5->-r ./repository/requirements.txt (line 6)) (0.44.0)\n",
      "Requirement already satisfied: wrapt~=1.12.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from tensorflow==2.5->-r ./repository/requirements.txt (line 6)) (1.12.1)\n",
      "Requirement already satisfied: gast==0.4.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from tensorflow==2.5->-r ./repository/requirements.txt (line 6)) (0.4.0)\n",
      "Requirement already satisfied: tensorboard~=2.5 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from tensorflow==2.5->-r ./repository/requirements.txt (line 6)) (2.11.2)\n",
      "Requirement already satisfied: tensorflow-estimator<2.6.0,>=2.5.0rc0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from tensorflow==2.5->-r ./repository/requirements.txt (line 6)) (2.5.0)\n",
      "Requirement already satisfied: keras-nightly~=2.5.0.dev in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from tensorflow==2.5->-r ./repository/requirements.txt (line 6)) (2.5.0.dev2021032900)\n",
      "Requirement already satisfied: grpcio~=1.34.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from tensorflow==2.5->-r ./repository/requirements.txt (line 6)) (1.34.1)\n",
      "Requirement already satisfied: threadpoolctl>=2.0.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from scikit-learn==0.24.1->-r ./repository/requirements.txt (line 7)) (3.5.0)\n",
      "Collecting scipy>=1.1 (from pymoo==0.4.2.2->-r ./repository/requirements.txt (line 5))\n",
      "  Using cached scipy-1.10.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (58 kB)\n",
      "Requirement already satisfied: setuptools in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from adversarial-robustness-toolbox==1.7.0->adversarial-robustness-toolbox[tensorflow]==1.7.0->-r ./repository/requirements.txt (line 10)) (75.1.0)\n",
      "Requirement already satisfied: numba~=0.53.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from adversarial-robustness-toolbox==1.7.0->adversarial-robustness-toolbox[tensorflow]==1.7.0->-r ./repository/requirements.txt (line 10)) (0.53.1)\n",
      "Requirement already satisfied: ply>=3.9 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (3.11)\n",
      "Requirement already satisfied: colorama>=0.3.9 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.4.6)\n",
      "Requirement already satisfied: configobj>=5.0.6 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (5.0.9)\n",
      "Requirement already satisfied: gitpython>3 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (3.1.43)\n",
      "Requirement already satisfied: dulwich>=0.20.23 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.22.4)\n",
      "Requirement already satisfied: pygit2>=1.5.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (1.13.3)\n",
      "Requirement already satisfied: nanotime>=0.5.2 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.5.2)\n",
      "Requirement already satisfied: pyasn1>=0.4.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.6.1)\n",
      "Requirement already satisfied: voluptuous>=0.11.7 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.14.2)\n",
      "Requirement already satisfied: jsonpath-ng>=1.5.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (1.7.0)\n",
      "Requirement already satisfied: requests>=2.22.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (2.32.3)\n",
      "Requirement already satisfied: grandalf==0.6 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.6)\n",
      "Requirement already satisfied: distro>=1.3.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (1.9.0)\n",
      "Requirement already satisfied: appdirs>=1.4.3 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (1.4.4)\n",
      "Requirement already satisfied: ruamel.yaml>=0.16.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.18.6)\n",
      "Requirement already satisfied: toml>=0.10.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.10.2)\n",
      "Requirement already satisfied: funcy>=1.14 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (2.0)\n",
      "Requirement already satisfied: pathspec>=0.6.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.12.1)\n",
      "Requirement already satisfied: shortuuid>=0.5.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (1.0.13)\n",
      "Requirement already satisfied: packaging>=19.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (24.1)\n",
      "Requirement already satisfied: zc.lockfile>=1.2.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (3.0.post1)\n",
      "Requirement already satisfied: flufl.lock<4,>=3.2 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (3.2)\n",
      "Requirement already satisfied: networkx~=2.5 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (2.8.8)\n",
      "Requirement already satisfied: psutil>=5.8.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (5.9.0)\n",
      "Requirement already satisfied: pydot>=1.2.4 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (1.4.2)\n",
      "Requirement already satisfied: flatten-dict<1,>=0.3.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.4.2)\n",
      "Requirement already satisfied: tabulate>=0.8.7 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.9.0)\n",
      "Requirement already satisfied: pygtrie>=2.3.2 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (2.5.0)\n",
      "Requirement already satisfied: dpath<3,>=2.0.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (2.2.0)\n",
      "Requirement already satisfied: shtab<2,>=1.3.4 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (1.7.1)\n",
      "Requirement already satisfied: rich>=10.0.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (12.0.1)\n",
      "Requirement already satisfied: dictdiffer>=0.8.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.9.0)\n",
      "Requirement already satisfied: python-benedict>=0.21.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.34.0)\n",
      "Requirement already satisfied: fsspec>=2021.6.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (2021.6.1)\n",
      "Requirement already satisfied: diskcache>=5.2.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (5.6.3)\n",
      "Requirement already satisfied: opencv-python>=4.0.0.21 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from pyrecorder==0.1.8->-r ./repository/requirements.txt (line 13)) (4.10.0.84)\n",
      "Requirement already satisfied: websocket-client>=0.55.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from comet-ml==3.13.1->-r ./repository/requirements.txt (line 15)) (1.8.0)\n",
      "Requirement already satisfied: requests-toolbelt>=0.8.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from comet-ml==3.13.1->-r ./repository/requirements.txt (line 15)) (1.0.0)\n",
      "Requirement already satisfied: wurlitzer>=1.0.2 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from comet-ml==3.13.1->-r ./repository/requirements.txt (line 15)) (3.1.1)\n",
      "Requirement already satisfied: nvidia-ml-py3>=7.352.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from comet-ml==3.13.1->-r ./repository/requirements.txt (line 15)) (7.352.0)\n",
      "Requirement already satisfied: jsonschema!=3.1.0,>=2.6.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from comet-ml==3.13.1->-r ./repository/requirements.txt (line 15)) (4.23.0)\n",
      "Requirement already satisfied: semantic-version>=2.8.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from comet-ml==3.13.1->-r ./repository/requirements.txt (line 15)) (2.10.0)\n",
      "Requirement already satisfied: everett>=1.0.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from everett[ini]>=1.0.1; python_version >= \"3.0\"->comet-ml==3.13.1->-r ./repository/requirements.txt (line 15)) (3.3.0)\n",
      "Requirement already satisfied: slicer==0.0.7 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from shap==0.39.0->-r ./repository/requirements.txt (line 16)) (0.0.7)\n",
      "Requirement already satisfied: cloudpickle in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from shap==0.39.0->-r ./repository/requirements.txt (line 16)) (3.1.0)\n",
      "Requirement already satisfied: tensorflow-addons in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from adversarial-robustness-toolbox[tensorflow]==1.7.0->-r ./repository/requirements.txt (line 10)) (0.21.0)\n",
      "Requirement already satisfied: gcsfs==2021.6.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (2021.6.1)\n",
      "Requirement already satisfied: s3fs==2021.6.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (2021.6.1)\n",
      "Requirement already satisfied: aiobotocore==1.3.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from aiobotocore[boto3]==1.3.0; extra == \"all\"->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (1.3.0)\n",
      "Requirement already satisfied: adlfs==0.7.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.7.1)\n",
      "Requirement already satisfied: azure-identity>=1.4.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (1.14.1)\n",
      "Requirement already satisfied: knack in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.12.0)\n",
      "Requirement already satisfied: paramiko>=2.7.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from paramiko[invoke]>=2.7.0; extra == \"all\"->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (3.5.0)\n",
      "Requirement already satisfied: oss2==2.6.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (2.6.1)\n",
      "Requirement already satisfied: pycryptodome>=3.10 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (3.21.0)\n",
      "Requirement already satisfied: pydrive2>=1.8.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (1.21.1)\n",
      "Requirement already satisfied: pyarrow>=2.0.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (17.0.0)\n",
      "Requirement already satisfied: hdfs==2.5.8 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (2.5.8)\n",
      "Requirement already satisfied: webdav4>=0.8.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.10.0)\n",
      "Requirement already satisfied: aiohttp in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from adlfs==0.7.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (3.10.11)\n",
      "Requirement already satisfied: azure-core>=1.5.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from adlfs==0.7.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (1.22.1)\n",
      "Requirement already satisfied: azure-datalake-store<0.1,>=0.0.46 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from adlfs==0.7.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.0.53)\n",
      "Requirement already satisfied: azure-storage-blob<12.7.0,>=12.5.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from adlfs==0.7.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (12.6.0)\n",
      "Requirement already satisfied: msrestazure in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from adlfs==0.7.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.6.4.post1)\n",
      "Requirement already satisfied: botocore<1.20.50,>=1.20.49 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from aiobotocore==1.3.0->aiobotocore[boto3]==1.3.0; extra == \"all\"->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (1.20.49)\n",
      "Requirement already satisfied: aioitertools>=0.5.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from aiobotocore==1.3.0->aiobotocore[boto3]==1.3.0; extra == \"all\"->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.8.0)\n",
      "Requirement already satisfied: boto3==1.17.49 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from aiobotocore[boto3]==1.3.0; extra == \"all\"->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (1.17.49)\n",
      "Requirement already satisfied: google-auth>=1.2 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from gcsfs==2021.6.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (2.36.0)\n",
      "Requirement already satisfied: google-auth-oauthlib in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from gcsfs==2021.6.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.4.6)\n",
      "Requirement already satisfied: decorator in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from gcsfs==2021.6.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (5.1.1)\n",
      "Requirement already satisfied: docopt in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from hdfs==2.5.8->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.6.2)\n",
      "Requirement already satisfied: crcmod>=1.7 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from oss2==2.6.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (1.7)\n",
      "Requirement already satisfied: aliyun-python-sdk-kms>=2.4.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from oss2==2.6.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (2.16.5)\n",
      "Requirement already satisfied: aliyun-python-sdk-core-v3>=2.5.5 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from oss2==2.6.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (2.13.33)\n",
      "Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from boto3==1.17.49->aiobotocore[boto3]==1.3.0; extra == \"all\"->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.10.0)\n",
      "Requirement already satisfied: s3transfer<0.4.0,>=0.3.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from boto3==1.17.49->aiobotocore[boto3]==1.3.0; extra == \"all\"->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.3.7)\n",
      "Requirement already satisfied: iniconfig in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from pytest->-r ./repository/requirements.txt (line 14)) (2.0.0)\n",
      "Requirement already satisfied: pluggy<2,>=1.5 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from pytest->-r ./repository/requirements.txt (line 14)) (1.5.0)\n",
      "Requirement already satisfied: exceptiongroup>=1.0.0rc8 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from pytest->-r ./repository/requirements.txt (line 14)) (1.2.0)\n",
      "Requirement already satisfied: tomli>=1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from pytest->-r ./repository/requirements.txt (line 14)) (2.0.1)\n",
      "Requirement already satisfied: cryptography>=2.5 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from azure-identity>=1.4.0->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (43.0.3)\n",
      "Requirement already satisfied: msal<2.0.0,>=1.20.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from azure-identity>=1.4.0->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (1.31.1)\n",
      "Requirement already satisfied: msal-extensions<2.0.0,>=0.3.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from azure-identity>=1.4.0->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (1.2.0)\n",
      "Requirement already satisfied: urllib3>=1.25 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from dulwich>=0.20.23->dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (1.26.20)\n",
      "Requirement already satisfied: atpublic in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from flufl.lock<4,>=3.2->dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (5.0)\n",
      "Requirement already satisfied: gitdb<5,>=4.0.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from gitpython>3->dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (4.0.11)\n",
      "Requirement already satisfied: attrs>=22.2.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from jsonschema!=3.1.0,>=2.6.0->comet-ml==3.13.1->-r ./repository/requirements.txt (line 15)) (24.2.0)\n",
      "Requirement already satisfied: importlib-resources>=1.4.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from jsonschema!=3.1.0,>=2.6.0->comet-ml==3.13.1->-r ./repository/requirements.txt (line 15)) (6.4.0)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from jsonschema!=3.1.0,>=2.6.0->comet-ml==3.13.1->-r ./repository/requirements.txt (line 15)) (2023.7.1)\n",
      "Requirement already satisfied: pkgutil-resolve-name>=1.3.10 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from jsonschema!=3.1.0,>=2.6.0->comet-ml==3.13.1->-r ./repository/requirements.txt (line 15)) (1.3.10)\n",
      "Requirement already satisfied: referencing>=0.28.4 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from jsonschema!=3.1.0,>=2.6.0->comet-ml==3.13.1->-r ./repository/requirements.txt (line 15)) (0.30.2)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from jsonschema!=3.1.0,>=2.6.0->comet-ml==3.13.1->-r ./repository/requirements.txt (line 15)) (0.10.6)\n",
      "Requirement already satisfied: llvmlite<0.37,>=0.36.0rc1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from numba~=0.53.1->adversarial-robustness-toolbox==1.7.0->adversarial-robustness-toolbox[tensorflow]==1.7.0->-r ./repository/requirements.txt (line 10)) (0.36.0)\n",
      "Requirement already satisfied: bcrypt>=3.2 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from paramiko>=2.7.0->paramiko[invoke]>=2.7.0; extra == \"all\"->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (4.2.1)\n",
      "Requirement already satisfied: pynacl>=1.5 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from paramiko>=2.7.0->paramiko[invoke]>=2.7.0; extra == \"all\"->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (1.5.0)\n",
      "Requirement already satisfied: invoke>=2.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from paramiko[invoke]>=2.7.0; extra == \"all\"->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (2.2.0)\n",
      "Requirement already satisfied: google-api-python-client>=1.12.5 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from pydrive2>=1.8.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (2.154.0)\n",
      "Requirement already satisfied: oauth2client>=4.0.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from pydrive2>=1.8.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (4.1.3)\n",
      "Requirement already satisfied: PyYAML>=3.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from pydrive2>=1.8.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (6.0.2)\n",
      "Requirement already satisfied: pyOpenSSL>=19.1.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from pydrive2>=1.8.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (24.2.1)\n",
      "Requirement already satisfied: cffi>=1.16.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from pygit2>=1.5.0->dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (1.17.1)\n",
      "Requirement already satisfied: python-fsutil<1.0.0,>=0.9.3 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from python-benedict>=0.21.1->dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.14.1)\n",
      "Requirement already satisfied: python-slugify<9.0.0,>=7.0.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from python-benedict>=0.21.1->dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (8.0.4)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from requests>=2.22.0->dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from requests>=2.22.0->dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (3.7)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from requests>=2.22.0->dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (2024.8.30)\n",
      "Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from rich>=10.0.0->dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.9.1)\n",
      "Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from rich>=10.0.0->dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (2.15.1)\n",
      "Requirement already satisfied: ruamel.yaml.clib>=0.2.7 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from ruamel.yaml>=0.16.1->dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.2.8)\n",
      "Requirement already satisfied: markdown>=2.6.8 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from tensorboard~=2.5->tensorflow==2.5->-r ./repository/requirements.txt (line 6)) (3.7)\n",
      "Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from tensorboard~=2.5->tensorflow==2.5->-r ./repository/requirements.txt (line 6)) (0.6.1)\n",
      "Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from tensorboard~=2.5->tensorflow==2.5->-r ./repository/requirements.txt (line 6)) (1.8.1)\n",
      "Requirement already satisfied: werkzeug>=1.0.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from tensorboard~=2.5->tensorflow==2.5->-r ./repository/requirements.txt (line 6)) (3.0.6)\n",
      "Requirement already satisfied: httpx<1,>=0.20 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from webdav4>=0.8.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.27.0)\n",
      "Requirement already satisfied: argcomplete in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from knack->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (3.5.1)\n",
      "Requirement already satisfied: typeguard<3.0.0,>=2.7 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from tensorflow-addons->adversarial-robustness-toolbox[tensorflow]==1.7.0->-r ./repository/requirements.txt (line 10)) (2.13.3)\n",
      "Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from aiohttp->adlfs==0.7.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (2.4.3)\n",
      "Requirement already satisfied: aiosignal>=1.1.2 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from aiohttp->adlfs==0.7.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (1.3.1)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from aiohttp->adlfs==0.7.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (1.5.0)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from aiohttp->adlfs==0.7.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (6.0.5)\n",
      "Requirement already satisfied: yarl<2.0,>=1.12.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from aiohttp->adlfs==0.7.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (1.15.2)\n",
      "Requirement already satisfied: async-timeout<6.0,>=4.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from aiohttp->adlfs==0.7.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (5.0.1)\n",
      "Requirement already satisfied: aliyun-python-sdk-core>=2.11.5 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from aliyun-python-sdk-kms>=2.4.1->oss2==2.6.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (2.16.0)\n",
      "Requirement already satisfied: msrest>=0.6.10 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from azure-storage-blob<12.7.0,>=12.5.0->adlfs==0.7.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.6.21)\n",
      "Requirement already satisfied: pycparser in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from cffi>=1.16.0->pygit2>=1.5.0->dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (2.21)\n",
      "Requirement already satisfied: smmap<6,>=3.0.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython>3->dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (5.0.1)\n",
      "Requirement already satisfied: httplib2<1.dev0,>=0.19.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from google-api-python-client>=1.12.5->pydrive2>=1.8.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.22.0)\n",
      "Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from google-api-python-client>=1.12.5->pydrive2>=1.8.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.2.0)\n",
      "Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from google-api-python-client>=1.12.5->pydrive2>=1.8.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (2.23.0)\n",
      "Requirement already satisfied: uritemplate<5,>=3.0.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from google-api-python-client>=1.12.5->pydrive2>=1.8.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (4.1.1)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from google-auth>=1.2->gcsfs==2021.6.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (5.5.0)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from google-auth>=1.2->gcsfs==2021.6.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.4.1)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from google-auth>=1.2->gcsfs==2021.6.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (4.9)\n",
      "Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from google-auth-oauthlib->gcsfs==2021.6.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (2.0.0)\n",
      "Requirement already satisfied: anyio in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from httpx<1,>=0.20->webdav4>=0.8.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (4.1.0)\n",
      "Requirement already satisfied: httpcore==1.* in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from httpx<1,>=0.20->webdav4>=0.8.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (1.0.2)\n",
      "Requirement already satisfied: sniffio in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from httpx<1,>=0.20->webdav4>=0.8.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (1.3.0)\n",
      "Requirement already satisfied: h11<0.15,>=0.13 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from httpcore==1.*->httpx<1,>=0.20->webdav4>=0.8.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.14.0)\n",
      "Requirement already satisfied: zipp>=3.1.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from importlib-resources>=1.4.0->jsonschema!=3.1.0,>=2.6.0->comet-ml==3.13.1->-r ./repository/requirements.txt (line 15)) (3.20.2)\n",
      "Requirement already satisfied: importlib-metadata>=4.4 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from markdown>=2.6.8->tensorboard~=2.5->tensorflow==2.5->-r ./repository/requirements.txt (line 6)) (7.0.1)\n",
      "Requirement already satisfied: PyJWT<3,>=1.0.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from PyJWT[crypto]<3,>=1.0.0->msal<2.0.0,>=1.20.0->azure-identity>=1.4.0->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (2.9.0)\n",
      "Requirement already satisfied: portalocker<3,>=1.4 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from msal-extensions<2.0.0,>=0.3.0->azure-identity>=1.4.0->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (2.10.1)\n",
      "Requirement already satisfied: text-unidecode>=1.3 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from python-slugify<9.0.0,>=7.0.0->python-benedict>=0.21.1->dvc==2.4.3->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (1.3)\n",
      "Requirement already satisfied: MarkupSafe>=2.1.1 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from werkzeug>=1.0.1->tensorboard~=2.5->tensorflow==2.5->-r ./repository/requirements.txt (line 6)) (2.1.3)\n",
      "Requirement already satisfied: adal<2.0.0,>=0.6.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from msrestazure->adlfs==0.7.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (1.2.7)\n",
      "Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client>=1.12.5->pydrive2>=1.8.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (1.66.0)\n",
      "Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client>=1.12.5->pydrive2>=1.8.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (1.25.0)\n",
      "Requirement already satisfied: isodate>=0.6.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from msrest>=0.6.10->azure-storage-blob<12.7.0,>=12.5.0->adlfs==0.7.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.7.2)\n",
      "Requirement already satisfied: oauthlib>=3.0.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib->gcsfs==2021.6.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (3.2.2)\n",
      "Requirement already satisfied: propcache>=0.2.0 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from yarl<2.0,>=1.12.0->aiohttp->adlfs==0.7.1->dvc[all]==2.4.3->-r ./repository/requirements.txt (line 11)) (0.2.0)\n",
      "Using cached scipy-1.10.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.5 MB)\n",
      "Installing collected packages: scipy\n",
      "  Attempting uninstall: scipy\n",
      "    Found existing installation: scipy 1.4.0\n",
      "    Uninstalling scipy-1.4.0:\n",
      "      Successfully uninstalled scipy-1.4.0\n",
      "Successfully installed scipy-1.10.1\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "Collecting scipy==1.4.0\n",
      "  Using cached scipy-1.4.0-cp38-cp38-manylinux1_x86_64.whl.metadata (2.0 kB)\n",
      "Requirement already satisfied: numpy>=1.13.3 in /home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages (from scipy==1.4.0) (1.19.5)\n",
      "Using cached scipy-1.4.0-cp38-cp38-manylinux1_x86_64.whl (26.0 MB)\n",
      "Installing collected packages: scipy\n",
      "  Attempting uninstall: scipy\n",
      "    Found existing installation: scipy 1.10.1\n",
      "    Uninstalling scipy-1.10.1:\n",
      "      Successfully uninstalled scipy-1.10.1\n",
      "\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "adversarial-robustness-toolbox 1.7.0 requires scipy>=1.4.1, but you have scipy 1.4.0 which is incompatible.\u001b[0m\u001b[31m\n",
      "\u001b[0mSuccessfully installed scipy-1.4.0\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "%pip install -r ./repository/requirements.txt\n",
    "%pip install scipy==1.4.0"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Download additional data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "--2024-11-29 17:35:36--  https://figshare.com/ndownloader/files/42088389?private_link=84ae808ce6999fafd192\n",
      "Resolving figshare.com (figshare.com)... 34.252.194.191, 54.72.17.176, 2a05:d018:1f4:d000:2ff1:256e:d815:335, ...\n",
      "Connecting to figshare.com (figshare.com)|34.252.194.191|:443... connected.\n",
      "HTTP request sent, awaiting response... 302 Found\n",
      "Location: https://s3-eu-west-1.amazonaws.com/pfigshare-u-files/42088389/IJCAI2022moevadata.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIYCQYOYV5JSSROOA/20241129/eu-west-1/s3/aws4_request&X-Amz-Date=20241129T163536Z&X-Amz-Expires=10&X-Amz-SignedHeaders=host&X-Amz-Signature=2348b0b2e69006fb8553c0fb3c562985e946c2e1ddaab6d8b7fc0ba550d4adb7 [following]\n",
      "--2024-11-29 17:35:36--  https://s3-eu-west-1.amazonaws.com/pfigshare-u-files/42088389/IJCAI2022moevadata.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIYCQYOYV5JSSROOA/20241129/eu-west-1/s3/aws4_request&X-Amz-Date=20241129T163536Z&X-Amz-Expires=10&X-Amz-SignedHeaders=host&X-Amz-Signature=2348b0b2e69006fb8553c0fb3c562985e946c2e1ddaab6d8b7fc0ba550d4adb7\n",
      "Resolving s3-eu-west-1.amazonaws.com (s3-eu-west-1.amazonaws.com)... 52.218.61.91, 52.218.116.200, 52.218.36.2, ...\n",
      "Connecting to s3-eu-west-1.amazonaws.com (s3-eu-west-1.amazonaws.com)|52.218.61.91|:443... connected.\n",
      "HTTP request sent, awaiting response... 200 OK\n",
      "Length: 170693689 (163M) [application/zip]\n",
      "Saving to: ‘moeva-data.zip’\n",
      "\n",
      "moeva-data.zip      100%[===================>] 162.79M  45.8MB/s    in 3.7s    \n",
      "\n",
      "2024-11-29 17:35:40 (44.1 MB/s) - ‘moeva-data.zip’ saved [170693689/170693689]\n",
      "\n",
      "Archive:  moeva-data.zip\n",
      "   creating: moeva-data/\n",
      "   creating: moeva-data/data/\n",
      "   creating: moeva-data/data/botnet/\n",
      "  inflating: moeva-data/data/botnet/X_test.npy  \n",
      "  inflating: moeva-data/data/botnet/X_train.npy  \n",
      "  inflating: moeva-data/data/botnet/y_test.npy  \n",
      "  inflating: moeva-data/data/botnet/y_train.npy  \n",
      "   creating: moeva-data/data/lcld/\n",
      "  inflating: moeva-data/data/lcld/dataset.csv  \n",
      "  inflating: moeva-data/data/lcld/X_test.npy  \n",
      "  inflating: moeva-data/data/lcld/X_train.npy  \n",
      "  inflating: moeva-data/data/lcld/y_test.npy  \n",
      "  inflating: moeva-data/data/lcld/y_train.npy  \n",
      "   creating: moeva-data/data/malware/\n",
      "  inflating: moeva-data/data/malware/features.csv  \n",
      "  inflating: moeva-data/data/malware/X_test.npy  \n",
      "  inflating: moeva-data/data/malware/X_train.npy  \n",
      "  inflating: moeva-data/data/malware/y_test.npy  \n",
      "  inflating: moeva-data/data/malware/y_train.npy  \n",
      "   creating: moeva-data/data/url/\n",
      "  inflating: moeva-data/data/url/features.csv  \n",
      "  inflating: moeva-data/data/url/url_data.csv  \n",
      "  inflating: moeva-data/data/url/X_test.npy  \n",
      "  inflating: moeva-data/data/url/X_train.npy  \n",
      "  inflating: moeva-data/data/url/y_test.npy  \n",
      "  inflating: moeva-data/data/url/y_train.npy  \n"
     ]
    }
   ],
   "source": [
    "!wget https://figshare.com/ndownloader/files/42088389?private_link=84ae808ce6999fafd192 -O moeva-data.zip\n",
    "!unzip moeva-data\n",
    "!mv ./moeva-data/data ./repository/data\n",
    "!rmdir moeva-data\n",
    "!rm moeva-data.zip"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/home/dev/Documents/Github/ai-security-project/repository\n"
     ]
    }
   ],
   "source": [
    "%cd ./repository/"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Replication"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:root:>>> Running seed 42 ...\n",
      "INFO:root:>>>>>> Running project rq1.lcld.static ...\n",
      "INFO:root:>>>>>>>>> Running budget 100 ...\n",
      "INFO:root:>>>>>>>>>>>> Running MoEvA ...\n",
      "INFO:root:['python', '-m', 'src.experiments.united.04_moeva', '-c', './config//moeva.yaml', '-c', './config//rq1.lcld.static.yaml', '-p', 'seed=42', '-p', 'budget=100', '-j', '{\"eps_list\":[0.2]}']\n",
      "2024-11-29 21:01:23.996021: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:01:23.996040: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "{'attack_name': 'moeva', 'n_pop': 200, 'n_offsprings': 100, 'project_name': 'lcld', 'paths': {'model': './models/lcld/nn.model', 'features': './data/lcld/features.csv', 'constraints': './data/lcld/constraints.csv', 'x_candidates': './data/lcld/x_candidates_common.npy', 'min_max_scaler': './models/lcld/scaler.joblib', 'ml_scaler': './models/lcld/scaler.joblib'}, 'dirs': {'results': './out/attacks/lcld/rq1/'}, 'misclassification_threshold': 0.25, 'norm': 2, 'n_initial_state': 1000, 'initial_state_offset': 0, 'system': {'n_jobs': 14, 'verbose': 1}, 'save_history': 'full', 'reconstruction': False, 'eps_list': [0.2], 'seed': 42, 'budget': 100}\n",
      "  1%|▌                                        | 14/1000 [00:00<00:17, 57.35it/s]2024-11-29 21:01:25.266215: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:01:25.266237: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:01:25.266448: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:01:25.266464: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:01:25.268652: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:01:25.268674: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:01:25.284916: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:01:25.284937: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:01:25.286576: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:01:25.286591: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:01:25.296398: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:01:25.296418: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:01:25.296948: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:01:25.296963: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:01:25.301285: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:01:25.301303: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:01:25.320016: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:01:25.320038: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:01:25.344375: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:01:25.344400: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:01:25.404007: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:01:25.404033: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:01:25.440104: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:01:25.440128: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:01:25.447503: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:01:25.447529: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:01:25.605267: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:01:25.605291: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:01:26.795867: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:01:26.795909: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:01:26.795935: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:01:26.796106: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-11-29 21:01:26.852752: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:01:26.852774: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:01:26.852789: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:01:26.852930: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-11-29 21:01:26.881151: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:01:26.881176: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:01:26.881193: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:01:26.881332: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-11-29 21:01:26.938938: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:01:26.938959: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:01:26.938973: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:01:26.939083: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-11-29 21:01:26.942008: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:01:26.942026: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:01:26.942040: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:01:26.942176: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-11-29 21:01:26.970384: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:01:26.970407: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:01:26.970423: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:01:26.970534: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-11-29 21:01:26.996815: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:01:26.996843: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:01:26.996862: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:01:26.996988: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-11-29 21:01:27.128334: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:01:27.128363: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:01:27.128385: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:01:27.128587: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-11-29 21:01:27.133289: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:01:27.133312: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:01:27.133368: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:01:27.133596: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-11-29 21:01:27.179941: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:01:27.179968: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:01:27.179988: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:01:27.180143: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-11-29 21:01:27.239237: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:01:27.239286: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:01:27.239318: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:01:27.239501: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-11-29 21:01:27.279568: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:01:27.279680: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:01:27.279706: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:01:27.279884: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-11-29 21:01:27.351717: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:01:27.351744: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:01:27.351764: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:01:27.351924: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-11-29 21:01:27.478846: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:01:27.478881: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:01:27.478907: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:01:27.479158: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "\n",
      "Compiled modules for significant speedup can not be used!\n",
      "https://pymoo.org/installation.html#installation\n",
      "\n",
      "To disable this warning:\n",
      "from pymoo.configuration import Configuration\n",
      "Configuration.show_compile_hint = False\n",
      "\n",
      "2024-11-29 21:01:29.214444: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)\n",
      "2024-11-29 21:01:29.214673: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 4192100000 Hz\n",
      "\n",
      "Compiled modules for significant speedup can not be used!\n",
      "https://pymoo.org/installation.html#installation\n",
      "\n",
      "To disable this warning:\n",
      "from pymoo.configuration import Configuration\n",
      "Configuration.show_compile_hint = False\n",
      "\n",
      "2024-11-29 21:01:29.534249: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)\n",
      "2024-11-29 21:01:29.534579: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 4192100000 Hz\n",
      "\n",
      "Compiled modules for significant speedup can not be used!\n",
      "https://pymoo.org/installation.html#installation\n",
      "\n",
      "To disable this warning:\n",
      "from pymoo.configuration import Configuration\n",
      "Configuration.show_compile_hint = False\n",
      "\n",
      "2024-11-29 21:01:29.570109: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)\n",
      "2024-11-29 21:01:29.570400: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 4192100000 Hz\n",
      "\n",
      "Compiled modules for significant speedup can not be used!\n",
      "https://pymoo.org/installation.html#installation\n",
      "\n",
      "To disable this warning:\n",
      "from pymoo.configuration import Configuration\n",
      "Configuration.show_compile_hint = False\n",
      "\n",
      "2024-11-29 21:01:29.619876: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)\n",
      "2024-11-29 21:01:29.620094: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 4192100000 Hz\n",
      "\n",
      "Compiled modules for significant speedup can not be used!\n",
      "https://pymoo.org/installation.html#installation\n",
      "\n",
      "To disable this warning:\n",
      "from pymoo.configuration import Configuration\n",
      "Configuration.show_compile_hint = False\n",
      "\n",
      "\n",
      "Compiled modules for significant speedup can not be used!\n",
      "https://pymoo.org/installation.html#installation\n",
      "\n",
      "To disable this warning:\n",
      "from pymoo.configuration import Configuration\n",
      "Configuration.show_compile_hint = False\n",
      "\n",
      "2024-11-29 21:01:29.732498: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)\n",
      "2024-11-29 21:01:29.732793: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 4192100000 Hz\n",
      "2024-11-29 21:01:29.746916: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)\n",
      "2024-11-29 21:01:29.747159: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 4192100000 Hz\n",
      "\n",
      "Compiled modules for significant speedup can not be used!\n",
      "https://pymoo.org/installation.html#installation\n",
      "\n",
      "To disable this warning:\n",
      "from pymoo.configuration import Configuration\n",
      "Configuration.show_compile_hint = False\n",
      "\n",
      "2024-11-29 21:01:29.784988: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)\n",
      "2024-11-29 21:01:29.785394: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 4192100000 Hz\n",
      "\n",
      "Compiled modules for significant speedup can not be used!\n",
      "https://pymoo.org/installation.html#installation\n",
      "\n",
      "To disable this warning:\n",
      "from pymoo.configuration import Configuration\n",
      "Configuration.show_compile_hint = False\n",
      "\n",
      "2024-11-29 21:01:29.828992: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)\n",
      "2024-11-29 21:01:29.829210: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 4192100000 Hz\n",
      "\n",
      "Compiled modules for significant speedup can not be used!\n",
      "https://pymoo.org/installation.html#installation\n",
      "\n",
      "To disable this warning:\n",
      "from pymoo.configuration import Configuration\n",
      "Configuration.show_compile_hint = False\n",
      "\n",
      "2024-11-29 21:01:29.858353: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)\n",
      "2024-11-29 21:01:29.858577: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 4192100000 Hz\n",
      "\n",
      "Compiled modules for significant speedup can not be used!\n",
      "https://pymoo.org/installation.html#installation\n",
      "\n",
      "To disable this warning:\n",
      "from pymoo.configuration import Configuration\n",
      "Configuration.show_compile_hint = False\n",
      "\n",
      "2024-11-29 21:01:29.888233: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)\n",
      "2024-11-29 21:01:29.888526: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 4192100000 Hz\n",
      "\n",
      "Compiled modules for significant speedup can not be used!\n",
      "https://pymoo.org/installation.html#installation\n",
      "\n",
      "To disable this warning:\n",
      "from pymoo.configuration import Configuration\n",
      "Configuration.show_compile_hint = False\n",
      "\n",
      "2024-11-29 21:01:29.910151: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)\n",
      "2024-11-29 21:01:29.910532: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 4192100000 Hz\n",
      "\n",
      "Compiled modules for significant speedup can not be used!\n",
      "https://pymoo.org/installation.html#installation\n",
      "\n",
      "To disable this warning:\n",
      "from pymoo.configuration import Configuration\n",
      "Configuration.show_compile_hint = False\n",
      "\n",
      "2024-11-29 21:01:29.960822: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)\n",
      "2024-11-29 21:01:29.961150: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 4192100000 Hz\n",
      "\n",
      "Compiled modules for significant speedup can not be used!\n",
      "https://pymoo.org/installation.html#installation\n",
      "\n",
      "To disable this warning:\n",
      "from pymoo.configuration import Configuration\n",
      "Configuration.show_compile_hint = False\n",
      "\n",
      "2024-11-29 21:01:30.131461: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)\n",
      "2024-11-29 21:01:30.131755: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 4192100000 Hz\n",
      "\n",
      "Compiled modules for significant speedup can not be used!\n",
      "https://pymoo.org/installation.html#installation\n",
      "\n",
      "To disable this warning:\n",
      "from pymoo.configuration import Configuration\n",
      "Configuration.show_compile_hint = False\n",
      "\n",
      "2024-11-29 21:01:30.255613: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)\n",
      "2024-11-29 21:01:30.255906: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 4192100000 Hz\n",
      " 25%|██████████                              | 252/1000 [02:49<08:52,  1.40it/s]2024-11-29 21:04:15.571705: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 73%|█████████████████████████████           | 728/1000 [08:32<03:17,  1.38it/s]2024-11-29 21:10:05.483221: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 77%|██████████████████████████████▊         | 770/1000 [09:02<02:43,  1.41it/s]2024-11-29 21:10:34.005028: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 87%|██████████████████████████████████▋     | 868/1000 [10:13<01:36,  1.37it/s]2024-11-29 21:11:48.124494: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 98%|███████████████████████████████████████▏| 980/1000 [11:35<00:14,  1.37it/s]2024-11-29 21:13:08.511789: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      "100%|███████████████████████████████████████| 1000/1000 [11:45<00:00,  1.42it/s]\n",
      "2024-11-29 21:14:00.499235: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:14:00.499356: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:14:00.499373: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:14:00.499518: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "  0%|                                                  | 0/1000 [00:00<?, ?it/s]2024-11-29 21:14:00.655247: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)\n",
      "2024-11-29 21:14:00.655471: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 4192100000 Hz\n",
      "100%|███████████████████████████████████████| 1000/1000 [00:15<00:00, 62.82it/s]\n",
      "func:'run' args:[(), {}] took: 772.0824 sec\n",
      "\u001b[0m\u001b[0m\u001b[0m\u001b[0m\u001b[0m\u001b[0m\u001b[0m\u001b[0m\u001b[0m\u001b[0m\u001b[0m\u001b[0m\u001b[0m\u001b[0m\u001b[0mINFO:root:>>>>>>>>>>>> Running pgd ...\n",
      "INFO:root:>>>>>>>>>>>>>>> Running eps 0.2 ...\n",
      "INFO:root:>>>>>>>>>>>>>>>>>> Running loss_evaluation flip ...\n",
      "INFO:root:['python', '-m', 'src.experiments.united.01_pgd_united', '-c', './config//pgd.yaml', '-c', './config//rq1.lcld.static.yaml', '-p', 'seed=42', '-p', 'budget=100', '-p', 'eps=0.2', '-p', 'loss_evaluation=flip']\n",
      "2024-11-29 21:14:18.709031: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:14:18.709048: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "/home/dev/Documents/Github/ai-security-project/repository/src/attacks/pgd/classifier.py:1: DeprecationWarning: The module art.classifiers will be removed in ART 1.8.0 and replaced with art.estimators.classification\n",
      "  from art.classifiers import TensorFlowV2Classifier\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:10: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  _nlv = LooseVersion(_np_version)\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:11: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  _np_version_under1p14 = _nlv < LooseVersion(\"1.14\")\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:12: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  _np_version_under1p15 = _nlv < LooseVersion(\"1.15\")\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:13: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  _np_version_under1p16 = _nlv < LooseVersion(\"1.16\")\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:14: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  _np_version_under1p17 = _nlv < LooseVersion(\"1.17\")\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:15: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  _np_version_under1p18 = _nlv < LooseVersion(\"1.18\")\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/setuptools/_distutils/version.py:337: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  other = LooseVersion(other)\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/function.py:114: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  if LooseVersion(_np_version) >= LooseVersion(\"1.17.0\"):\n",
      "2024-11-29 21:14:20.238414: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:14:20.238432: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:14:20.238444: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:14:20.238546: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "  0%|                                                  | 0/1000 [00:00<?, ?it/s]2024-11-29 21:14:21.013206: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)\n",
      "2024-11-29 21:14:21.013447: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 4192100000 Hz\n",
      "100%|███████████████████████████████████████| 1000/1000 [00:14<00:00, 70.56it/s]\n",
      "    o1     o2   o3   o4   o5     o6   o7\n",
      "0  0.0  0.211  1.0  0.0  0.0  0.211  0.0\n",
      "\u001b[0mINFO:root:>>>>>>>>>>>>>>>>>> Running loss_evaluation flip+sat ...\n",
      "INFO:root:['python', '-m', 'src.experiments.united.01_pgd_united', '-c', './config//pgd.yaml', '-c', './config//rq1.lcld.static.yaml', '-p', 'seed=42', '-p', 'budget=100', '-p', 'eps=0.2', '-p', 'loss_evaluation=flip+sat']\n",
      "2024-11-29 21:14:35.995915: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:14:35.995936: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "/home/dev/Documents/Github/ai-security-project/repository/src/attacks/pgd/classifier.py:1: DeprecationWarning: The module art.classifiers will be removed in ART 1.8.0 and replaced with art.estimators.classification\n",
      "  from art.classifiers import TensorFlowV2Classifier\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:10: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  _nlv = LooseVersion(_np_version)\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:11: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  _np_version_under1p14 = _nlv < LooseVersion(\"1.14\")\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:12: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  _np_version_under1p15 = _nlv < LooseVersion(\"1.15\")\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:13: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  _np_version_under1p16 = _nlv < LooseVersion(\"1.16\")\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:14: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  _np_version_under1p17 = _nlv < LooseVersion(\"1.17\")\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:15: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  _np_version_under1p18 = _nlv < LooseVersion(\"1.18\")\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/setuptools/_distutils/version.py:337: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  other = LooseVersion(other)\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/function.py:114: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  if LooseVersion(_np_version) >= LooseVersion(\"1.17.0\"):\n",
      "2024-11-29 21:14:37.030573: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:14:37.030595: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:14:37.030608: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:14:37.030718: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "  1%|▌                                       | 14/1000 [00:00<00:08, 121.42it/s]2024-11-29 21:14:38.039560: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:14:38.039559: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:14:38.039578: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:14:38.039579: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:14:38.039776: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:14:38.039790: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:14:38.040209: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:14:38.040224: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:14:38.101777: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:14:38.101807: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:14:38.101858: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:14:38.101880: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:14:38.111184: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:14:38.111207: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:14:38.122112: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:14:38.122135: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:14:38.175293: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:14:38.175317: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:14:38.184288: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:14:38.184311: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:14:38.187728: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:14:38.187749: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:14:38.212093: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:14:38.212140: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:14:38.241403: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:14:38.241424: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:14:38.386182: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:14:38.386206: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "Error code 10009: License expired 2022-01-13\n",
      "Error code 10009: License expired 2022-01-13Error code 10009: License expired 2022-01-13\n",
      "\n",
      "  3%|█▏                                       | 28/1000 [00:01<00:37, 25.79it/s]Error code 10009: License expired 2022-01-13\n",
      "Error code 10009: License expired 2022-01-13\n",
      "Error code 10009: License expired 2022-01-13\n",
      "Error code 10009: License expired 2022-01-13\n",
      "Error code 10009: License expired 2022-01-13\n",
      "Error code 10009: License expired 2022-01-13\n",
      "Error code 10009: License expired 2022-01-13\n",
      "Error code 10009: License expired 2022-01-13\n",
      "Error code 10009: License expired 2022-01-13\n",
      "Error code 10009: License expired 2022-01-13\n",
      "Error code 10009: License expired 2022-01-13\n",
      "Error code 10009: License expired 2022-01-13\n",
      "Error code 10009: License expired 2022-01-13\n",
      "Error code 10009: License expired 2022-01-13\n",
      "Error code 10009: License expired 2022-01-13\n",
      "Error code 10009: License expired 2022-01-13\n",
      "Error code 10009: License expired 2022-01-13\n",
      "Error code 10009: License expired 2022-01-13\n",
      "Error code 10009: License expired 2022-01-13\n",
      "Error code 10009: License expired 2022-01-13\n",
      "joblib.externals.loky.process_executor._RemoteTraceback: \n",
      "\"\"\"\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py\", line 431, in _process_worker\n",
      "    r = call_item()\n",
      "  File \"/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py\", line 285, in __call__\n",
      "    return self.fn(*self.args, **self.kwargs)\n",
      "  File \"/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/joblib/_parallel_backends.py\", line 593, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/joblib/parallel.py\", line 252, in __call__\n",
      "    return [func(*args, **kwargs)\n",
      "  File \"/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/joblib/parallel.py\", line 252, in <listcomp>\n",
      "    return [func(*args, **kwargs)\n",
      "  File \"/home/dev/Documents/Github/ai-security-project/repository/src/attacks/sat/sat.py\", line 195, in _one_generate\n",
      "    return solutions\n",
      "UnboundLocalError: local variable 'solutions' referenced before assignment\n",
      "\"\"\"\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dev/miniconda3/envs/moeva2/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/home/dev/miniconda3/envs/moeva2/lib/python3.8/runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/home/dev/Documents/Github/ai-security-project/repository/src/experiments/united/01_pgd_united.py\", line 220, in <module>\n",
      "    run()\n",
      "  File \"/home/dev/Documents/Github/ai-security-project/repository/src/experiments/united/01_pgd_united.py\", line 154, in run\n",
      "    x_attacks = attack.generate(x_initial, x_attacks)\n",
      "  File \"/home/dev/Documents/Github/ai-security-project/repository/src/attacks/sat/sat.py\", line 227, in generate\n",
      "    Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/joblib/parallel.py\", line 1042, in __call__\n",
      "    self.retrieve()\n",
      "  File \"/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/joblib/parallel.py\", line 921, in retrieve\n",
      "    self._output.extend(job.get(timeout=self.timeout))\n",
      "  File \"/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/joblib/_parallel_backends.py\", line 540, in wrap_future_result\n",
      "    return future.result(timeout=timeout)\n",
      "  File \"/home/dev/miniconda3/envs/moeva2/lib/python3.8/concurrent/futures/_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"/home/dev/miniconda3/envs/moeva2/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "UnboundLocalError: local variable 'solutions' referenced before assignment\n",
      "  3%|█▏                                       | 28/1000 [00:02<01:13, 13.18it/s]\n",
      "INFO:root:>>>>>>>>>>>>>>>>>> Running loss_evaluation constraints+flip ...\n",
      "INFO:root:['python', '-m', 'src.experiments.united.01_pgd_united', '-c', './config//pgd.yaml', '-c', './config//rq1.lcld.static.yaml', '-p', 'seed=42', '-p', 'budget=100', '-p', 'eps=0.2', '-p', 'loss_evaluation=constraints+flip']\n",
      "2024-11-29 21:14:40.379660: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:14:40.379678: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "/home/dev/Documents/Github/ai-security-project/repository/src/attacks/pgd/classifier.py:1: DeprecationWarning: The module art.classifiers will be removed in ART 1.8.0 and replaced with art.estimators.classification\n",
      "  from art.classifiers import TensorFlowV2Classifier\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:10: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  _nlv = LooseVersion(_np_version)\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:11: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  _np_version_under1p14 = _nlv < LooseVersion(\"1.14\")\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:12: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  _np_version_under1p15 = _nlv < LooseVersion(\"1.15\")\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:13: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  _np_version_under1p16 = _nlv < LooseVersion(\"1.16\")\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:14: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  _np_version_under1p17 = _nlv < LooseVersion(\"1.17\")\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:15: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  _np_version_under1p18 = _nlv < LooseVersion(\"1.18\")\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/setuptools/_distutils/version.py:337: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  other = LooseVersion(other)\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/function.py:114: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  if LooseVersion(_np_version) >= LooseVersion(\"1.17.0\"):\n",
      "2024-11-29 21:14:41.438461: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:14:41.438490: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:14:41.438508: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:14:41.438617: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "  0%|                                                  | 0/1000 [00:00<?, ?it/s]2024-11-29 21:14:42.510718: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)\n",
      "2024-11-29 21:14:42.511010: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 4192100000 Hz\n",
      "100%|███████████████████████████████████████| 1000/1000 [00:14<00:00, 70.71it/s]\n",
      "    o1     o2   o3   o4   o5     o6   o7\n",
      "0  0.0  0.324  1.0  0.0  0.0  0.324  0.0\n",
      "\u001b[0mINFO:root:>>>>>>>>>>>>>>>>>> Running loss_evaluation constraints+flip+adaptive_eps_step ...\n",
      "INFO:root:['python', '-m', 'src.experiments.united.01_pgd_united', '-c', './config//pgd.yaml', '-c', './config//rq1.lcld.static.yaml', '-p', 'seed=42', '-p', 'budget=100', '-p', 'eps=0.2', '-p', 'loss_evaluation=constraints+flip+adaptive_eps_step']\n",
      "2024-11-29 21:14:57.352376: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:14:57.352397: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "/home/dev/Documents/Github/ai-security-project/repository/src/attacks/pgd/classifier.py:1: DeprecationWarning: The module art.classifiers will be removed in ART 1.8.0 and replaced with art.estimators.classification\n",
      "  from art.classifiers import TensorFlowV2Classifier\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:10: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  _nlv = LooseVersion(_np_version)\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:11: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  _np_version_under1p14 = _nlv < LooseVersion(\"1.14\")\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:12: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  _np_version_under1p15 = _nlv < LooseVersion(\"1.15\")\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:13: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  _np_version_under1p16 = _nlv < LooseVersion(\"1.16\")\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:14: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  _np_version_under1p17 = _nlv < LooseVersion(\"1.17\")\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:15: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  _np_version_under1p18 = _nlv < LooseVersion(\"1.18\")\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/setuptools/_distutils/version.py:337: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  other = LooseVersion(other)\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/function.py:114: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  if LooseVersion(_np_version) >= LooseVersion(\"1.17.0\"):\n",
      "2024-11-29 21:14:58.437292: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:14:58.437314: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:14:58.437331: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:14:58.437450: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "PGD - Batches: 0it [00:00, ?it/s]1.0: 0.0199999\n",
      "1.0: 0.0199999\n",
      "1.0: 0.0199999\n",
      "1.0: 0.0199999\n",
      "1.0: 0.0199999\n",
      "1.0: 0.0199999\n",
      "1.0: 0.0199999\n",
      "1.0: 0.0199999\n",
      "1.0: 0.0199999\n",
      "1.0: 0.0199999\n",
      "1.0: 0.0199999\n",
      "1.0: 0.0199999\n",
      "1.0: 0.0199999\n",
      "1.0: 0.0199999\n",
      "2.0: 0.00199999\n",
      "2.0: 0.00199999\n",
      "2.0: 0.00199999\n",
      "2.0: 0.00199999\n",
      "2.0: 0.00199999\n",
      "2.0: 0.00199999\n",
      "2.0: 0.00199999\n",
      "2.0: 0.00199999\n",
      "2.0: 0.00199999\n",
      "2.0: 0.00199999\n",
      "2.0: 0.00199999\n",
      "2.0: 0.00199999\n",
      "2.0: 0.00199999\n",
      "2.0: 0.00199999\n",
      "3.0: 0.00019999900000000002\n",
      "3.0: 0.00019999900000000002\n",
      "3.0: 0.00019999900000000002\n",
      "3.0: 0.00019999900000000002\n",
      "3.0: 0.00019999900000000002\n",
      "3.0: 0.00019999900000000002\n",
      "3.0: 0.00019999900000000002\n",
      "3.0: 0.00019999900000000002\n",
      "3.0: 0.00019999900000000002\n",
      "3.0: 0.00019999900000000002\n",
      "3.0: 0.00019999900000000002\n",
      "3.0: 0.00019999900000000002\n",
      "3.0: 0.00019999900000000002\n",
      "3.0: 0.00019999900000000002\n",
      "4.0: 1.99999e-05\n",
      "4.0: 1.99999e-05\n",
      "4.0: 1.99999e-05\n",
      "4.0: 1.99999e-05\n",
      "4.0: 1.99999e-05\n",
      "4.0: 1.99999e-05\n",
      "4.0: 1.99999e-05\n",
      "4.0: 1.99999e-05\n",
      "4.0: 1.99999e-05\n",
      "4.0: 1.99999e-05\n",
      "4.0: 1.99999e-05\n",
      "4.0: 1.99999e-05\n",
      "4.0: 1.99999e-05\n",
      "4.0: 1.99999e-05\n",
      "5.0: 1.99999e-06\n",
      "5.0: 1.99999e-06\n",
      "5.0: 1.99999e-06\n",
      "5.0: 1.99999e-06\n",
      "5.0: 1.99999e-06\n",
      "5.0: 1.99999e-06\n",
      "5.0: 1.99999e-06\n",
      "5.0: 1.99999e-06\n",
      "5.0: 1.99999e-06\n",
      "5.0: 1.99999e-06\n",
      "5.0: 1.99999e-06\n",
      "5.0: 1.99999e-06\n",
      "5.0: 1.99999e-06\n",
      "5.0: 1.99999e-06\n",
      "6.0: 1.99999e-07\n",
      "6.0: 1.99999e-07\n",
      "6.0: 1.99999e-07\n",
      "6.0: 1.99999e-07\n",
      "6.0: 1.99999e-07\n",
      "6.0: 1.99999e-07\n",
      "6.0: 1.99999e-07\n",
      "6.0: 1.99999e-07\n",
      "6.0: 1.99999e-07\n",
      "6.0: 1.99999e-07\n",
      "6.0: 1.99999e-07\n",
      "6.0: 1.99999e-07\n",
      "6.0: 1.99999e-07\n",
      "6.0: 1.99999e-07\n",
      "7.0: 1.99999e-08\n",
      "7.0: 1.99999e-08\n",
      "7.0: 1.99999e-08\n",
      "7.0: 1.99999e-08\n",
      "7.0: 1.99999e-08\n",
      "7.0: 1.99999e-08\n",
      "7.0: 1.99999e-08\n",
      "7.0: 1.99999e-08\n",
      "7.0: 1.99999e-08\n",
      "7.0: 1.99999e-08\n",
      "7.0: 1.99999e-08\n",
      "7.0: 1.99999e-08\n",
      "7.0: 1.99999e-08\n",
      "7.0: 1.99999e-08\n",
      "8.0: 1.9999900000000002e-09\n",
      "8.0: 1.9999900000000002e-09\n",
      "  0%|                                                  | 0/1000 [00:00<?, ?it/s]2024-11-29 21:14:59.561856: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)\n",
      "2024-11-29 21:14:59.562087: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 4192100000 Hz\n",
      "100%|███████████████████████████████████████| 1000/1000 [00:14<00:00, 70.55it/s]\n",
      "    o1     o2   o3   o4   o5     o6   o7\n",
      "0  0.0  0.014  1.0  0.0  0.0  0.014  0.0\n",
      "\u001b[0mINFO:root:>>>>>>>>>>>>>>>>>> Running loss_evaluation constraints+flip+adaptive_eps_step+repair ...\n",
      "INFO:root:['python', '-m', 'src.experiments.united.01_pgd_united', '-c', './config//pgd.yaml', '-c', './config//rq1.lcld.static.yaml', '-p', 'seed=42', '-p', 'budget=100', '-p', 'eps=0.2', '-p', 'loss_evaluation=constraints+flip+adaptive_eps_step+repair']\n",
      "2024-11-29 21:15:14.484968: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:15:14.484986: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "/home/dev/Documents/Github/ai-security-project/repository/src/attacks/pgd/classifier.py:1: DeprecationWarning: The module art.classifiers will be removed in ART 1.8.0 and replaced with art.estimators.classification\n",
      "  from art.classifiers import TensorFlowV2Classifier\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:10: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  _nlv = LooseVersion(_np_version)\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:11: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  _np_version_under1p14 = _nlv < LooseVersion(\"1.14\")\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:12: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  _np_version_under1p15 = _nlv < LooseVersion(\"1.15\")\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:13: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  _np_version_under1p16 = _nlv < LooseVersion(\"1.16\")\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:14: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  _np_version_under1p17 = _nlv < LooseVersion(\"1.17\")\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:15: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  _np_version_under1p18 = _nlv < LooseVersion(\"1.18\")\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/setuptools/_distutils/version.py:337: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  other = LooseVersion(other)\n",
      "/home/dev/miniconda3/envs/moeva2/lib/python3.8/site-packages/pandas/compat/numpy/function.py:114: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  if LooseVersion(_np_version) >= LooseVersion(\"1.17.0\"):\n",
      "2024-11-29 21:15:15.559226: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:15:15.559245: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:15:15.559258: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:15:15.559368: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "PGD - Batches: 0it [00:00, ?it/s]1.0: 0.0199999\n",
      "1.0: 0.0199999\n",
      "1.0: 0.0199999\n",
      "1.0: 0.0199999\n",
      "1.0: 0.0199999\n",
      "1.0: 0.0199999\n",
      "1.0: 0.0199999\n",
      "1.0: 0.0199999\n",
      "1.0: 0.0199999\n",
      "1.0: 0.0199999\n",
      "1.0: 0.0199999\n",
      "1.0: 0.0199999\n",
      "1.0: 0.0199999\n",
      "1.0: 0.0199999\n",
      "2.0: 0.00199999\n",
      "2.0: 0.00199999\n",
      "2.0: 0.00199999\n",
      "2.0: 0.00199999\n",
      "2.0: 0.00199999\n",
      "2.0: 0.00199999\n",
      "2.0: 0.00199999\n",
      "2.0: 0.00199999\n",
      "2.0: 0.00199999\n",
      "2.0: 0.00199999\n",
      "2.0: 0.00199999\n",
      "2.0: 0.00199999\n",
      "2.0: 0.00199999\n",
      "2.0: 0.00199999\n",
      "3.0: 0.00019999900000000002\n",
      "3.0: 0.00019999900000000002\n",
      "3.0: 0.00019999900000000002\n",
      "3.0: 0.00019999900000000002\n",
      "3.0: 0.00019999900000000002\n",
      "3.0: 0.00019999900000000002\n",
      "3.0: 0.00019999900000000002\n",
      "3.0: 0.00019999900000000002\n",
      "3.0: 0.00019999900000000002\n",
      "3.0: 0.00019999900000000002\n",
      "3.0: 0.00019999900000000002\n",
      "3.0: 0.00019999900000000002\n",
      "3.0: 0.00019999900000000002\n",
      "3.0: 0.00019999900000000002\n",
      "4.0: 1.99999e-05\n",
      "4.0: 1.99999e-05\n",
      "4.0: 1.99999e-05\n",
      "4.0: 1.99999e-05\n",
      "4.0: 1.99999e-05\n",
      "4.0: 1.99999e-05\n",
      "4.0: 1.99999e-05\n",
      "4.0: 1.99999e-05\n",
      "4.0: 1.99999e-05\n",
      "4.0: 1.99999e-05\n",
      "4.0: 1.99999e-05\n",
      "4.0: 1.99999e-05\n",
      "4.0: 1.99999e-05\n",
      "4.0: 1.99999e-05\n",
      "5.0: 1.99999e-06\n",
      "5.0: 1.99999e-06\n",
      "5.0: 1.99999e-06\n",
      "5.0: 1.99999e-06\n",
      "5.0: 1.99999e-06\n",
      "5.0: 1.99999e-06\n",
      "5.0: 1.99999e-06\n",
      "5.0: 1.99999e-06\n",
      "5.0: 1.99999e-06\n",
      "5.0: 1.99999e-06\n",
      "5.0: 1.99999e-06\n",
      "5.0: 1.99999e-06\n",
      "5.0: 1.99999e-06\n",
      "5.0: 1.99999e-06\n",
      "6.0: 1.99999e-07\n",
      "6.0: 1.99999e-07\n",
      "6.0: 1.99999e-07\n",
      "6.0: 1.99999e-07\n",
      "6.0: 1.99999e-07\n",
      "6.0: 1.99999e-07\n",
      "6.0: 1.99999e-07\n",
      "6.0: 1.99999e-07\n",
      "6.0: 1.99999e-07\n",
      "6.0: 1.99999e-07\n",
      "6.0: 1.99999e-07\n",
      "6.0: 1.99999e-07\n",
      "6.0: 1.99999e-07\n",
      "6.0: 1.99999e-07\n",
      "7.0: 1.99999e-08\n",
      "7.0: 1.99999e-08\n",
      "7.0: 1.99999e-08\n",
      "7.0: 1.99999e-08\n",
      "7.0: 1.99999e-08\n",
      "7.0: 1.99999e-08\n",
      "7.0: 1.99999e-08\n",
      "7.0: 1.99999e-08\n",
      "7.0: 1.99999e-08\n",
      "7.0: 1.99999e-08\n",
      "7.0: 1.99999e-08\n",
      "7.0: 1.99999e-08\n",
      "7.0: 1.99999e-08\n",
      "7.0: 1.99999e-08\n",
      "8.0: 1.9999900000000002e-09\n",
      "8.0: 1.9999900000000002e-09\n",
      "  0%|                                                  | 0/1000 [00:00<?, ?it/s]2024-11-29 21:15:16.741839: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)\n",
      "2024-11-29 21:15:16.742099: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 4192100000 Hz\n",
      "100%|███████████████████████████████████████| 1000/1000 [00:14<00:00, 69.67it/s]\n",
      "      o1     o2   o3     o4     o5     o6     o7\n",
      "0  0.535  0.063  1.0  0.034  0.535  0.063  0.034\n",
      "\u001b[0mINFO:root:>>>>>>>>> Running budget 1000 ...\n",
      "INFO:root:>>>>>>>>>>>> Running MoEvA ...\n",
      "INFO:root:['python', '-m', 'src.experiments.united.04_moeva', '-c', './config//moeva.yaml', '-c', './config//rq1.lcld.static.yaml', '-p', 'seed=42', '-p', 'budget=1000', '-j', '{\"eps_list\":[0.2]}']\n",
      "2024-11-29 21:15:31.829100: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:15:31.829118: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "{'attack_name': 'moeva', 'n_pop': 200, 'n_offsprings': 100, 'project_name': 'lcld', 'paths': {'model': './models/lcld/nn.model', 'features': './data/lcld/features.csv', 'constraints': './data/lcld/constraints.csv', 'x_candidates': './data/lcld/x_candidates_common.npy', 'min_max_scaler': './models/lcld/scaler.joblib', 'ml_scaler': './models/lcld/scaler.joblib'}, 'dirs': {'results': './out/attacks/lcld/rq1/'}, 'misclassification_threshold': 0.25, 'norm': 2, 'n_initial_state': 1000, 'initial_state_offset': 0, 'system': {'n_jobs': 14, 'verbose': 1}, 'save_history': 'full', 'reconstruction': False, 'eps_list': [0.2], 'seed': 42, 'budget': 1000}\n",
      "  1%|▌                                        | 14/1000 [00:00<00:15, 63.69it/s]2024-11-29 21:15:33.111665: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:15:33.111665: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:15:33.111687: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:15:33.111688: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:15:33.112400: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:15:33.112413: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:15:33.137267: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:15:33.137291: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:15:33.137826: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:15:33.137842: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:15:33.140714: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:15:33.140728: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:15:33.142145: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:15:33.142160: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:15:33.144082: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:15:33.144095: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:15:33.194045: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:15:33.194069: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:15:33.252713: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:15:33.252736: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:15:33.312502: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:15:33.312535: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:15:33.328591: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:15:33.328611: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:15:33.418849: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:15:33.418868: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:15:33.420119: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:15:33.420135: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2024-11-29 21:15:34.709676: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:15:34.709701: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:15:34.709722: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:15:34.709876: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-11-29 21:15:34.725099: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:15:34.725134: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:15:34.725156: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:15:34.725297: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-11-29 21:15:34.801089: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:15:34.801114: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:15:34.801134: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:15:34.801268: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-11-29 21:15:34.841974: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:15:34.842007: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:15:34.842026: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:15:34.842170: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-11-29 21:15:34.881243: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:15:34.881272: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:15:34.881289: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:15:34.881415: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-11-29 21:15:34.881805: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:15:34.881823: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:15:34.881838: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:15:34.881977: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-11-29 21:15:34.926220: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:15:34.926324: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:15:34.926349: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:15:34.926577: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-11-29 21:15:34.979184: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:15:34.979205: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:15:34.979218: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:15:34.979334: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-11-29 21:15:34.988639: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:15:34.988665: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:15:34.988692: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:15:34.988845: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-11-29 21:15:35.036488: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:15:35.036513: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:15:35.036595: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:15:35.036795: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-11-29 21:15:35.294554: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:15:35.294587: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:15:35.294605: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:15:35.294776: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-11-29 21:15:35.345753: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:15:35.345832: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:15:35.345886: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:15:35.346084: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-11-29 21:15:35.538947: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:15:35.539007: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:15:35.539037: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:15:35.539203: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-11-29 21:15:35.633577: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2024-11-29 21:15:35.633604: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2024-11-29 21:15:35.633620: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (debianvm): /proc/driver/nvidia/version does not exist\n",
      "2024-11-29 21:15:35.633751: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "\n",
      "Compiled modules for significant speedup can not be used!\n",
      "https://pymoo.org/installation.html#installation\n",
      "\n",
      "To disable this warning:\n",
      "from pymoo.configuration import Configuration\n",
      "Configuration.show_compile_hint = False\n",
      "\n",
      "2024-11-29 21:15:37.195118: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)\n",
      "2024-11-29 21:15:37.195405: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 4192100000 Hz\n",
      "\n",
      "Compiled modules for significant speedup can not be used!\n",
      "https://pymoo.org/installation.html#installation\n",
      "\n",
      "To disable this warning:\n",
      "from pymoo.configuration import Configuration\n",
      "Configuration.show_compile_hint = False\n",
      "\n",
      "2024-11-29 21:15:37.276751: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)\n",
      "2024-11-29 21:15:37.277065: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 4192100000 Hz\n",
      "\n",
      "Compiled modules for significant speedup can not be used!\n",
      "https://pymoo.org/installation.html#installation\n",
      "\n",
      "To disable this warning:\n",
      "from pymoo.configuration import Configuration\n",
      "Configuration.show_compile_hint = False\n",
      "\n",
      "2024-11-29 21:15:37.363674: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)\n",
      "2024-11-29 21:15:37.363974: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 4192100000 Hz\n",
      "\n",
      "Compiled modules for significant speedup can not be used!\n",
      "https://pymoo.org/installation.html#installation\n",
      "\n",
      "To disable this warning:\n",
      "from pymoo.configuration import Configuration\n",
      "Configuration.show_compile_hint = False\n",
      "\n",
      "2024-11-29 21:15:37.628199: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)\n",
      "2024-11-29 21:15:37.628697: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 4192100000 Hz\n",
      "\n",
      "Compiled modules for significant speedup can not be used!\n",
      "https://pymoo.org/installation.html#installation\n",
      "\n",
      "To disable this warning:\n",
      "from pymoo.configuration import Configuration\n",
      "Configuration.show_compile_hint = False\n",
      "\n",
      "2024-11-29 21:15:37.735099: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)\n",
      "2024-11-29 21:15:37.735351: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 4192100000 Hz\n",
      "\n",
      "Compiled modules for significant speedup can not be used!\n",
      "https://pymoo.org/installation.html#installation\n",
      "\n",
      "To disable this warning:\n",
      "from pymoo.configuration import Configuration\n",
      "Configuration.show_compile_hint = False\n",
      "\n",
      "2024-11-29 21:15:37.757581: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)\n",
      "2024-11-29 21:15:37.757879: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 4192100000 Hz\n",
      "\n",
      "Compiled modules for significant speedup can not be used!\n",
      "https://pymoo.org/installation.html#installation\n",
      "\n",
      "To disable this warning:\n",
      "from pymoo.configuration import Configuration\n",
      "Configuration.show_compile_hint = False\n",
      "\n",
      "2024-11-29 21:15:37.850835: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)\n",
      "2024-11-29 21:15:37.851101: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 4192100000 Hz\n",
      "\n",
      "Compiled modules for significant speedup can not be used!\n",
      "https://pymoo.org/installation.html#installation\n",
      "\n",
      "To disable this warning:\n",
      "from pymoo.configuration import Configuration\n",
      "Configuration.show_compile_hint = False\n",
      "\n",
      "2024-11-29 21:15:37.883658: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)\n",
      "2024-11-29 21:15:37.883972: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 4192100000 Hz\n",
      "\n",
      "Compiled modules for significant speedup can not be used!\n",
      "https://pymoo.org/installation.html#installation\n",
      "\n",
      "To disable this warning:\n",
      "from pymoo.configuration import Configuration\n",
      "Configuration.show_compile_hint = False\n",
      "\n",
      "2024-11-29 21:15:37.918546: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)\n",
      "2024-11-29 21:15:37.918850: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 4192100000 Hz\n",
      "\n",
      "Compiled modules for significant speedup can not be used!\n",
      "https://pymoo.org/installation.html#installation\n",
      "\n",
      "To disable this warning:\n",
      "from pymoo.configuration import Configuration\n",
      "Configuration.show_compile_hint = False\n",
      "\n",
      "2024-11-29 21:15:37.963918: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)\n",
      "2024-11-29 21:15:37.964118: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 4192100000 Hz\n",
      "\n",
      "Compiled modules for significant speedup can not be used!\n",
      "https://pymoo.org/installation.html#installation\n",
      "\n",
      "To disable this warning:\n",
      "from pymoo.configuration import Configuration\n",
      "Configuration.show_compile_hint = False\n",
      "\n",
      "2024-11-29 21:15:38.017064: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)\n",
      "2024-11-29 21:15:38.017269: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 4192100000 Hz\n",
      "\n",
      "Compiled modules for significant speedup can not be used!\n",
      "https://pymoo.org/installation.html#installation\n",
      "\n",
      "To disable this warning:\n",
      "from pymoo.configuration import Configuration\n",
      "Configuration.show_compile_hint = False\n",
      "\n",
      "\n",
      "Compiled modules for significant speedup can not be used!\n",
      "https://pymoo.org/installation.html#installation\n",
      "\n",
      "To disable this warning:\n",
      "from pymoo.configuration import Configuration\n",
      "Configuration.show_compile_hint = False\n",
      "\n",
      "2024-11-29 21:15:38.061433: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)\n",
      "2024-11-29 21:15:38.061648: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 4192100000 Hz\n",
      "2024-11-29 21:15:38.064681: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)\n",
      "2024-11-29 21:15:38.064932: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 4192100000 Hz\n",
      "\n",
      "Compiled modules for significant speedup can not be used!\n",
      "https://pymoo.org/installation.html#installation\n",
      "\n",
      "To disable this warning:\n",
      "from pymoo.configuration import Configuration\n",
      "Configuration.show_compile_hint = False\n",
      "\n",
      "2024-11-29 21:15:38.115887: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)\n",
      "2024-11-29 21:15:38.116125: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 4192100000 Hz\n",
      "  3%|█▏                                       | 28/1000 [01:17<27:04,  1.67s/it]2024-11-29 21:17:54.444495: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      "  4%|█▋                                       | 42/1000 [02:33<44:36,  2.79s/it]2024-11-29 21:18:13.771927: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      "2024-11-29 21:19:21.680432: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      "  6%|██▎                                      | 56/1000 [03:50<56:39,  3.60s/it]2024-11-29 21:20:07.578204: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      "  7%|██▋                                    | 70/1000 [05:06<1:04:24,  4.16s/it]2024-11-29 21:20:40.927332: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      "2024-11-29 21:20:55.686602: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      "  8%|███▎                                   | 84/1000 [06:23<1:09:31,  4.55s/it]2024-11-29 21:22:34.160499: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 10%|███▊                                   | 98/1000 [07:40<1:12:52,  4.85s/it]2024-11-29 21:24:25.008639: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 11%|████▎                                 | 112/1000 [08:58<1:15:00,  5.07s/it]2024-11-29 21:25:39.988052: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 14%|█████▎                                | 140/1000 [11:35<1:16:32,  5.34s/it]2024-11-29 21:27:24.711584: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      "2024-11-29 21:27:28.632503: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 15%|█████▊                                | 154/1000 [12:54<1:16:23,  5.42s/it]2024-11-29 21:29:12.114514: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 17%|██████▍                               | 168/1000 [14:13<1:16:11,  5.49s/it]2024-11-29 21:29:49.572617: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 20%|███████▍                              | 196/1000 [16:48<1:13:51,  5.51s/it]2024-11-29 21:33:25.603692: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 21%|███████▉                              | 210/1000 [18:05<1:12:38,  5.52s/it]2024-11-29 21:34:07.395573: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      "2024-11-29 21:34:36.688489: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 22%|████████▌                             | 224/1000 [19:22<1:11:15,  5.51s/it]2024-11-29 21:35:21.896633: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      "2024-11-29 21:35:50.364499: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 25%|█████████▌                            | 252/1000 [21:57<1:08:51,  5.52s/it]2024-11-29 21:38:33.864364: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 27%|██████████                            | 266/1000 [23:14<1:07:20,  5.50s/it]2024-11-29 21:39:01.948494: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 34%|████████████▊                         | 336/1000 [29:39<1:01:01,  5.51s/it]2024-11-29 21:46:01.771430: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      "2024-11-29 21:46:15.903865: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      "2024-11-29 21:46:25.067687: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 35%|██████████████                          | 350/1000 [30:56<59:43,  5.51s/it]2024-11-29 21:47:44.773138: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 36%|██████████████▌                         | 364/1000 [32:12<58:10,  5.49s/it]2024-11-29 21:48:59.659872: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 38%|███████████████                         | 378/1000 [33:30<57:00,  5.50s/it]2024-11-29 21:49:56.528490: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      "2024-11-29 21:50:11.730006: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 39%|███████████████▋                        | 392/1000 [34:45<55:29,  5.48s/it]2024-11-29 21:50:46.621727: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      "2024-11-29 21:51:15.713675: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 43%|█████████████████▎                      | 434/1000 [38:36<51:46,  5.49s/it]2024-11-29 21:55:07.856388: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      "2024-11-29 21:55:22.857916: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 45%|█████████████████▉                      | 448/1000 [39:53<50:32,  5.49s/it]2024-11-29 21:55:36.624340: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 48%|███████████████████                     | 476/1000 [42:29<48:19,  5.53s/it]2024-11-29 21:58:44.976508: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      "2024-11-29 21:59:15.642845: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 49%|███████████████████▌                    | 490/1000 [43:46<46:58,  5.53s/it]2024-11-29 21:59:31.496297: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 52%|████████████████████▋                   | 518/1000 [46:22<44:34,  5.55s/it]2024-11-29 22:02:03.298805: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 53%|█████████████████████▎                  | 532/1000 [47:40<43:20,  5.56s/it]2024-11-29 22:03:37.396530: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 55%|█████████████████████▊                  | 546/1000 [48:58<42:06,  5.57s/it]2024-11-29 22:05:07.706138: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 56%|██████████████████████▍                 | 560/1000 [50:14<40:29,  5.52s/it]2024-11-29 22:06:46.656161: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 59%|███████████████████████▌                | 588/1000 [52:50<38:10,  5.56s/it]2024-11-29 22:08:41.272713: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      "2024-11-29 22:09:38.896717: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 60%|████████████████████████                | 602/1000 [54:07<36:43,  5.54s/it]2024-11-29 22:10:17.879389: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 63%|█████████████████████████▏              | 630/1000 [56:40<33:55,  5.50s/it]2024-11-29 22:12:51.166819: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      "2024-11-29 22:13:30.208050: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 67%|█████████████████████████▌            | 672/1000 [1:00:28<29:47,  5.45s/it]2024-11-29 22:16:07.437104: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      "2024-11-29 22:16:47.006508: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      "2024-11-29 22:16:50.029068: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      "2024-11-29 22:17:05.728101: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 69%|██████████████████████████            | 686/1000 [1:01:46<28:40,  5.48s/it]2024-11-29 22:17:47.586997: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 70%|██████████████████████████▌           | 700/1000 [1:03:02<27:18,  5.46s/it]2024-11-29 22:18:53.391976: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      "2024-11-29 22:19:27.090437: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 71%|███████████████████████████▏          | 714/1000 [1:04:20<26:09,  5.49s/it]2024-11-29 22:20:00.925860: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 74%|████████████████████████████▏         | 742/1000 [1:06:57<23:54,  5.56s/it]2024-11-29 22:23:26.852502: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 76%|████████████████████████████▋         | 756/1000 [1:08:13<22:29,  5.53s/it]2024-11-29 22:23:56.859301: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      "2024-11-29 22:24:20.296500: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 77%|█████████████████████████████▎        | 770/1000 [1:09:30<21:10,  5.53s/it]2024-11-29 22:25:25.177355: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      "2024-11-29 22:25:47.971221: W tensorflow/core/kernels/data/model_dataset_op.cc:205] Optimization loop failed: Cancelled: Operation was cancelled\n",
      " 78%|█████████████████████████████▊        | 784/1000 [1:10:48<19:55,  5.53s/it]"
     ]
    }
   ],
   "source": [
    "# Required imports\n",
    "import sys\n",
    "# Add current directory to Python path\n",
    "sys.path.append('./')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Run RQ1 experiment for LCLD data\n",
    "!python -m src.run_rq1 -c ./config/rq1.lcld.yaml"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "moeva2",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.20"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
